### ISSUE TITLE
Insert statements are disordered

### ISSUE THREAD

**Issue by ngosang** [devrimgunduz/pagila#12]
I can't execute the file with inserts because the queries order violates the FKs.
For example, the city and country tables are inserted after address.
Please, reorder the inserts.

**Comment by devrimgunduz** [comment]
Can you please paste the steps, error messages and PostgreSQL versions? Cannot reproduce here.

**Comment by ngosang** [comment]
Of course.
1) I configure a Postgres 9 in my local machine using the official Docker image
2) I configure DBeaver to connect to the Postgres
3) I open the file `pagila-schema.sql` in Dbeaver
4) I run all SQL sentences in order (there is a button on the left to run all lines) => OK
5) I open the file `pagila-insert-data.sql` in DBeaver
6) I run all SQL sentences in order => ERROR
7) You will get errors in some inserts due to FK violations

**Comment by devrimgunduz** [comment]
Hi,

(First of all: There is no Postgres 9. 9.0 to 9.6 are all major versions)

As written in readme, never versions of pagila are compatible on PostgreSQL 11 and above.

Regards, Devrim

**Comment by rpgd60** [comment]
I have a similar problem, using Postgres 12 running on Kubuntu 20.10
I am not using docker.   Using Postgres 12 installed directly using the 
I attach a file describing the environment and the steps to reproduce.

[pagila.import.error.postgres.12.txt](https://github.com/devrimgunduz/pagila/files/5946507/pagila.import.error.postgres.12.txt)

**Comment by ngosang** [comment]
Tested with Postgres 9.6 and Postgres 11, both fails.

**Comment by devrimgunduz** [comment]
Hi,

Sorry for the delay. Just fixed this issue. Will wrap a new release today.

Regards, Devrim
