### ISSUE TITLE
Where is screenshot showing schema design?

### ISSUE THREAD

**Issue by encryptblockr** [devrimgunduz/pagila#22]
At the very least we want to quickly see the table relations in an ERD diagram
Any plan to include like a screenshot to quickly see how the table relationships look like?
For an example schema design, i think that should be obvious

**Comment by dwhitemv25** [comment]
There is a diagram in the MySQL Sakila documentation:

https://dev.mysql.com/doc/sakila/en/sakila-structure.html

**Comment by Qoyyuum** [comment]
@encryptblockr please have a look at #26 . Its auto generated from pgAdmin. Hard to read but that's how many tables with many relationships sort of look like.

**Comment by devrimgunduz** [comment]
Thanks! This is now in git head. It will appear in next release.
