### ISSUE TITLE
payment.payment_id missing PRIMARY KEY constraint

### ISSUE THREAD

**Issue by dwhitemv25** [devrimgunduz/pagila#23]
In the original Sakila schema, the `payment_id` column in the `payment` table has a PRIMARY KEY constraint. Pagila does not. 
I found this by accident when I restored a backup of pagila over itself and duplicated all the rows in the partitioned tables.

Because `payment_date` is the partition key, it would have to be defined as
```
ALTER TABLE payment ADD PRIMARY KEY (payment_date, payment_id)
```

**Comment by devrimgunduz** [comment]
Hi,

Thanks for the report. Committed a fix. It will appear in next release.
