### ISSUE TITLE
More diverse data

### ISSUE THREAD

**Issue by jonjensen** [devrimgunduz/pagila#28]
Would you welcome pull requests to diversify the data a bit?

For example:

* Even though there are 6 languages in the `language` table, only English (id 1) appears in the `film` table.
* No film has more than one category assigned even though it's a many-to-many relationship.
* Only one rental has more than one payment.
* There are only 2 stores and 2 staff.

More variety would make practice query results more interesting and help people see the need to GROUP BY etc.

**Comment by seeken** [comment]
Also

- all release years are 2006
- All actors have pretty much all ratings with only a couple missing the full set

**Comment by devrimgunduz** [comment]
Hi @jonjensen ,

Apologies for the late reply. Yes, of course. A patch will be appreciated.

Regards,

**Comment by mgramin** [comment]
Hi @jonjensen @devrimgunduz,
I have prepared a PR, please take a look when you have a chance - https://github.com/devrimgunduz/pagila/pull/30
