### ISSUE TITLE
Customer table sequence and duplicate key errors

### ISSUE THREAD

**Issue by aklaver** [devrimgunduz/pagila#4]
In pagila-schema.sql there is this:

--
-- Name: customer_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE customer_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE customer_customer_id_seq OWNER TO postgres;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE customer (
    customer_id SERIAL PRIMARY KEY,
    ...

Unfortunately what you end up with is:

pagila_(postgres)# \d customer
                                            Table "public.customer"
   Column    |           Type           | Collation | Nullable |                    Default                     
-------------+--------------------------+-----------+----------+------------------------------------------------
 customer_id | integer                  |           | not null | nextval('customer_customer_id_seq1'::regclass)

pagila_(postgres)# \d customer_customer_id_seq1
             Sequence "public.customer_customer_id_seq1"
  Type   | Start | Minimum |  Maximum   | Increment | Cycles? | Cache 
---------+-------+---------+------------+-----------+---------+-------
 integer |     1 |       1 | 2147483647 |         1 | no      |     1
Owned by: public.customer.customer_id

The SERIAL as 'type' for customer_id causes Postgres to create a new sequence bound to the field with a Start value of 1. This means inserting new data fails with duplicate key errors.

A quick scan through the rest of pagila-schema.sql shows that this is the only place this done. The rest of the CREATE TABLE statements follow the pattern:

id_fld fld_type DEFAULT nextval('some_seq'::regclass) NOT NULL,

**Comment by devrimgunduz** [comment]
Thanks for the  patch. Closing.
