### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timneedham** [devrimgunduz/pagila#9]
Hi,

Thanks for doing this, great stuff! 

I'd to include Pagila as part of some test fixtures in my current project... would that be OK?
If it's not too much of a pain, might it be possible to slap a `LICENSE.md` file or similar in there please?

Thanks again!

**Comment by devrimgunduz** [comment]
Hi,

It's PostgreSQL licenced. Feel free to include it. Next version will include a license file.

**Comment by devrimgunduz** [comment]
Already committed LICENSE file, will appear in next release. Closing.
